####################################################################################
#                                      SERVER                                      #
####################################################################################
server:
  port: 8080

####################################################################################
#                                      SPRING                                      #
####################################################################################
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/treasure?serverTimezone=UTC&useLegacyDatetimeCode=false&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: rootroot
  sql:
    init:
      # always | embedded | never
      mode: never
      data-locations: classpath:data/test.sql
  jpa:
    hibernate:
      # create | create-drop | none | update | validate
      ddl-auto: create

####################################################################################
#                                      CUSTOM                                      #
####################################################################################


####################################################################################
#                                     LOGGING                                      #
####################################################################################
logging:
  # TRACE | DEBUG | INFO | WARN | ERROR | FATAL
  level:
    # project
    com.jakers.treasure: DEBUG
    # hibernate
    org.hibernate.SQL: DEBUG
    # hibernate query params
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    # hibernate query performance
    org.hibernate.stat: DEBUG
    # hikari CP
    com.zaxxer.hikari: DEBUG
    # jdbc query params
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE